title: The Welch Lab
email: welchjd@med.umich.edu
description: > # this means to ignore newlines until "baseurl:"
  Our research aims to address fundamental problems in both biomedical research and computer science by developing new tools tailored to rapidly emerging high-throughput sequencing technologies. Broadly, we seek to understand what genes define the complement of cell types and cell states within healthy tissue, how cells differentiate to their final fates, and how dysregulation of genes within specific cell types contributes to human disease. As computational method developers, we seek to both employ and advance the methods of machine learning, particularly for unsupervised analysis of high-dimensional data.
baseurl: ""
url: "https://welch-lab.github.io"
